const u = (id, w = 1400) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`

export const CATEGORIES = [
  { id: 'furniture', en: 'Furniture', ru: 'Мебель' },
  { id: 'lighting', en: 'Lighting', ru: 'Свет' },
  { id: 'textiles', en: 'Textiles', ru: 'Текстиль' },
  { id: 'ceramics', en: 'Ceramics', ru: 'Керамика' },
  { id: 'accessories', en: 'Objects', ru: 'Объекты' },
]

export const MATERIALS = [
  { id: 'oak', en: 'Oak', ru: 'Дуб' },
  { id: 'wool', en: 'Wool', ru: 'Шерсть' },
  { id: 'linen', en: 'Linen', ru: 'Лён' },
  { id: 'brass', en: 'Brass', ru: 'Латунь' },
  { id: 'ceramic', en: 'Ceramic', ru: 'Керамика' },
  { id: 'glass', en: 'Glass', ru: 'Стекло' },
  { id: 'walnut', en: 'Walnut', ru: 'Орех' },
]

export const PRODUCTS = [
  {
    id: 'arhus-lounge',
    sku: 'FJ-CHR-014',
    category: 'furniture',
    material: 'wool',
    name: { en: 'Århus Lounge Chair', ru: 'Кресло Århus' },
    blurb: { en: 'Low, quiet, endlessly sit-able.', ru: 'Низкое, спокойное, в нём хочется остаться.' },
    description: {
      en: 'A compact lounge chair with a kiln-dried oak frame and a dense wool-blend seat. The slightly reclined back and wide arm make it a reading chair first — not a sculpture that happens to have legs. Upholstered in Riga.',
      ru: 'Компактное кресло на каркасе из дуба камерной сушки и плотным сиденьем из шерсти. Слегка отклонённая спинка и широкий подлокотник — это кресло для чтения, а не скульптура с ножками. Обивка шьётся в Риге.',
    },
    care: {
      en: 'Vacuum with a soft brush. Blot spills immediately. Professional clean only.',
      ru: 'Пылесосить мягкой насадкой. Пятна промокать сразу. Только профессиональная чистка.',
    },
    price: 640,
    compareAt: null,
    stock: 7,
    images: [
      u('photo-1567538096630-e0c55bd6374c'),
      u('photo-1598300042247-d088f8ab3a91'),
      u('photo-1580480055273-228ff5388ef8'),
    ],
    colors: [
      { id: 'clay', hex: '#c4a574', en: 'Clay', ru: 'Глина' },
      { id: 'ink', hex: '#2c2a28', en: 'Ink', ru: 'Чернила' },
      { id: 'fog', hex: '#cfc8be', en: 'Fog', ru: 'Туман' },
    ],
    sizes: null,
    dims: '78 × 82 × 74 cm',
    origin: { en: 'Riga, Latvia', ru: 'Рига, Латвия' },
    weight: 18,
    tags: ['bestseller'],
    featured: true,
    createdAt: '2026-02-12',
  },
  {
    id: 'kalmar-table',
    sku: 'FJ-TBL-003',
    category: 'furniture',
    material: 'oak',
    name: { en: 'Kalmar Dining Table', ru: 'Обеденный стол Kalmar' },
    blurb: { en: 'One slab. No theatre.', ru: 'Одна столешница. Без театра.' },
    description: {
      en: 'Solid European oak, brushed and finished with a hardwax oil that will take the marks of family life rather than fight them. The trestle is quietly engineered so six people sit without knocking a knee.',
      ru: 'Массив европейского дуба, брашированный и закрытый твёрдым маслом-воском — он принимает следы жизни, а не борется с ними. Подстолье рассчитано так, чтобы шестеро сидели, не задевая коленом.',
    },
    care: {
      en: 'Wipe with a damp cloth. Re-oil once a year. Use trivets for heat.',
      ru: 'Протирать влажной тканью. Раз в год обновлять масло. Горячее — на подставки.',
    },
    price: 1290,
    compareAt: 1490,
    stock: 4,
    images: [
      u('photo-1533090481720-856c6e3c1fdc'),
      u('photo-1611967164521-abae8fba4668'),
      u('photo-1499939667766-4afceb292d05'),
    ],
    colors: [
      { id: 'natural', hex: '#c9a36b', en: 'Natural oak', ru: 'Натуральный дуб' },
      { id: 'smoked', hex: '#6b5344', en: 'Smoked', ru: 'Копчёный' },
    ],
    sizes: ['180 cm', '220 cm'],
    dims: '180/220 × 90 × 75 cm',
    origin: { en: 'Kuldiga, Latvia', ru: 'Кулдига, Латвия' },
    weight: 48,
    tags: ['sale'],
    featured: true,
    createdAt: '2025-11-02',
  },
  {
    id: 'norr-sofa',
    sku: 'FJ-SOF-001',
    category: 'furniture',
    material: 'wool',
    name: { en: 'Norr Modular Sofa', ru: 'Модульный диван Norr' },
    blurb: { en: 'A landscape, not a block.', ru: 'Пейзаж, а не блок.' },
    description: {
      en: 'Deep seats, removable covers, and a modular logic that can grow from a two-seater to an L when the apartment does. Feather-wrapped foam keeps the sit soft without collapsing by Thursday.',
      ru: 'Глубокая посадка, съёмные чехлы и модульная логика: от двушки до Г-образного, когда квартира вырастет. Пена в пере пера держит мягкость и не проседает к четвергу.',
    },
    care: {
      en: 'Covers are removable and dry-clean only. Rotate cushions monthly.',
      ru: 'Чехлы снимаются, только химчистка. Подушки переворачивать раз в месяц.',
    },
    price: 2180,
    compareAt: null,
    stock: 3,
    images: [
      u('photo-1555041469-a586c61ea9bc'),
      u('photo-1578500494198-246f612d3b3d'),
      u('photo-1540574163026-643ea20ade25'),
    ],
    colors: [
      { id: 'sage', hex: '#6d7a68', en: 'Sage', ru: 'Шалфей' },
      { id: 'sand', hex: '#d8cbb8', en: 'Sand', ru: 'Песок' },
      { id: 'charcoal', hex: '#3a3937', en: 'Charcoal', ru: 'Уголь' },
    ],
    sizes: ['2-seat', '3-seat', 'L-shape'],
    dims: 'From 210 × 98 × 78 cm',
    origin: { en: 'Riga, Latvia', ru: 'Рига, Латвия' },
    weight: 72,
    tags: ['bestseller', 'new'],
    featured: true,
    createdAt: '2026-04-18',
  },
  {
    id: 'venta-bench',
    sku: 'FJ-BNC-008',
    category: 'furniture',
    material: 'oak',
    name: { en: 'Venta Oak Bench', ru: 'Скамья Venta' },
    blurb: { en: 'Hallway, table, window — it does not mind.', ru: 'Прихожая, стол, окно — ей всё равно.' },
    description: {
      en: 'A slim solid-oak bench with a faintly scooped seat. Useful at the dining table, under a window, or as the first and last surface of the day by the door.',
      ru: 'Тонкая скамья из массива дуба с едва заметной выемкой сиденья. К столу, под окно или у двери — первая и последняя поверхность дня.',
    },
    care: {
      en: 'Dust and occasional oil. Avoid standing water.',
      ru: 'Пыль и иногда масло. Не оставлять лужи.',
    },
    price: 420,
    compareAt: null,
    stock: 11,
    images: [
      u('photo-1594026112284-02bb6f3352fe'),
      u('photo-1506439773649-6e0eb8cfb237'),
      u('photo-1519710164239-da123dc03ef4'),
    ],
    colors: [{ id: 'oak', hex: '#c4a574', en: 'Oak', ru: 'Дуб' }],
    sizes: ['140 cm', '180 cm'],
    dims: '140/180 × 35 × 45 cm',
    origin: { en: 'Cesis, Latvia', ru: 'Цесис, Латвия' },
    weight: 14,
    tags: [],
    featured: false,
    createdAt: '2025-09-20',
  },
  {
    id: 'signe-sideboard',
    sku: 'FJ-CAB-006',
    category: 'furniture',
    material: 'walnut',
    name: { en: 'Signe Sideboard', ru: 'Комод Signe' },
    blurb: { en: 'Doors that close like a whisper.', ru: 'Двери закрываются шёпотом.' },
    description: {
      en: 'American walnut veneer over a stable birch core, with push-latches and adjustable oak shelves. Designed to hold records, linen or the good glasses — not to announce itself from across the room.',
      ru: 'Шпон американского ореха на стабильном берёзовом каркасе, пуш-защёлки и полки из дуба. Для пластинок, льна или хороших бокалов — а не чтобы кричать через комнату.',
    },
    care: {
      en: 'Dust with a dry cloth. No silicone sprays.',
      ru: 'Протирать сухой тканью. Без силиконовых спреев.',
    },
    price: 980,
    compareAt: null,
    stock: 5,
    images: [
      u('photo-1595428774223-ef52624120d2'),
      u('photo-1595428774111-70fb87e3d71e'),
      u('photo-1618220179428-22790b461013'),
    ],
    colors: [
      { id: 'walnut', hex: '#5a3d2b', en: 'Walnut', ru: 'Орех' },
      { id: 'oak', hex: '#c4a574', en: 'Oak', ru: 'Дуб' },
    ],
    sizes: null,
    dims: '180 × 45 × 72 cm',
    origin: { en: 'Riga, Latvia', ru: 'Рига, Латвия' },
    weight: 52,
    tags: ['new'],
    featured: true,
    createdAt: '2026-05-03',
  },
  {
    id: 'havn-coffee',
    sku: 'FJ-TBL-011',
    category: 'furniture',
    material: 'oak',
    name: { en: 'Havn Coffee Table', ru: 'Журнальный стол Havn' },
    blurb: { en: 'A quiet island for books and tea.', ru: 'Тихий остров для книг и чая.' },
    description: {
      en: 'Two stacked planes of oak with a hidden lower shelf. The edges are eased by hand so the table feels finished even when you bump it in the dark.',
      ru: 'Две дубовые плоскости и скрытая нижняя полка. Кромки смягчены вручную — стол остаётся законченным, даже если задеть его в темноте.',
    },
    care: {
      en: 'Wipe dry. Coasters help, they are not a religion.',
      ru: 'Протирать насухо. Подставки помогают, но это не религия.',
    },
    price: 540,
    compareAt: null,
    stock: 9,
    images: [
      u('photo-1616046229478-9901c5536a45'),
      u('photo-1631679706909-1844bbd07221'),
      u('photo-1586023492125-27b2c045efd7'),
    ],
    colors: [{ id: 'oak', hex: '#c4a574', en: 'Oak', ru: 'Дуб' }],
    sizes: null,
    dims: '110 × 60 × 38 cm',
    origin: { en: 'Liepaja, Latvia', ru: 'Лиепая, Латвия' },
    weight: 22,
    tags: [],
    featured: false,
    createdAt: '2026-01-14',
  },
  {
    id: 'lumen-floor',
    sku: 'FJ-LMP-021',
    category: 'lighting',
    material: 'linen',
    name: { en: 'Lumen Paper Floor Lamp', ru: 'Торшер Lumen' },
    blurb: { en: 'A second window after dusk.', ru: 'Второе окно после заката.' },
    description: {
      en: 'A tall rice-paper shade on a blackened steel stem. The light is even and unashamedly soft — for evenings when overhead lighting would be a mistake.',
      ru: 'Высокий абажур из рисовой бумаги на чернёной стальной ноге. Свет ровный и нарочито мягкий — для вечеров, когда верхний свет был бы ошибкой.',
    },
    care: {
      en: 'Dust with a feather. E27 LED 6–8W, warm 2700K.',
      ru: 'Смахивать пыль. Лампа E27 LED 6–8Вт, 2700K.',
    },
    price: 290,
    compareAt: null,
    stock: 14,
    images: [
      u('photo-1540932239986-30128078f3c5'),
      u('photo-1513506003901-1e6a229e2d15'),
      u('photo-1507473885765-e6ed057f782c'),
    ],
    colors: [
      { id: 'ivory', hex: '#f3eadc', en: 'Ivory', ru: 'Слоновая кость' },
      { id: 'black', hex: '#1c1b19', en: 'Black stem', ru: 'Чёрная нога' },
    ],
    sizes: null,
    dims: 'Ø 48 × 158 cm',
    origin: { en: 'Tallinn / Riga', ru: 'Таллин / Рига' },
    weight: 6,
    tags: ['bestseller'],
    featured: true,
    createdAt: '2025-12-01',
  },
  {
    id: 'orb-pendant',
    sku: 'FJ-LMP-018',
    category: 'lighting',
    material: 'brass',
    name: { en: 'Orb Brass Pendant', ru: 'Подвес Orb' },
    blurb: { en: 'A small sun over the table.', ru: 'Небольшое солнце над столом.' },
    description: {
      en: 'Spun brass, left unlacquered so it will deepen with the years. Hang one over a table or three in a loose line down a corridor.',
      ru: 'Точёная латунь без лака — с годами она темнеет. Один над столом или три свободной линией вдоль коридора.',
    },
    care: {
      en: 'Leave the patina or polish with a brass cloth. E27.',
      ru: 'Оставить патину или полировать салфеткой для латуни. E27.',
    },
    price: 210,
    compareAt: 250,
    stock: 16,
    images: [
      u('photo-1551298370-9d3d53740c72'),
      u('photo-1617104678098-de229db51175'),
      u('photo-1513506003901-1e6a229e2d15'),
    ],
    colors: [
      { id: 'brass', hex: '#c4a056', en: 'Raw brass', ru: 'Сырая латунь' },
      { id: 'black', hex: '#2a2825', en: 'Blackened', ru: 'Чернёная' },
    ],
    sizes: null,
    dims: 'Ø 22 × 24 cm, 3 m cable',
    origin: { en: 'Helsinki', ru: 'Хельсинки' },
    weight: 1.8,
    tags: ['sale'],
    featured: false,
    createdAt: '2025-08-22',
  },
  {
    id: 'alba-lamp',
    sku: 'FJ-LMP-027',
    category: 'lighting',
    material: 'ceramic',
    name: { en: 'Alba Table Lamp', ru: 'Настольная лампа Alba' },
    blurb: { en: 'Clay, linen, a late chapter.', ru: 'Глина, лён, поздняя глава.' },
    description: {
      en: 'A thrown stoneware base with a gathered linen shade. The switch sits on the cord so you never have to hunt behind the books.',
      ru: 'Точёное каменное основание и собранный льняной абажур. Выключатель на шнуре — не нужно искать его за книгами.',
    },
    care: {
      en: 'Wipe the base. Shade: gentle vacuum. E14 LED.',
      ru: 'Основание протирать. Абажур — мягкий пылесос. E14 LED.',
    },
    price: 165,
    compareAt: null,
    stock: 10,
    images: [
      u('photo-1507473885765-e6ed057f782c'),
      u('photo-1513506003901-1e6a229e2d15'),
      u('photo-1540932239986-30128078f3c5'),
    ],
    colors: [
      { id: 'sand', hex: '#d7c4a3', en: 'Sand', ru: 'Песок' },
      { id: 'moss', hex: '#5d6b58', en: 'Moss', ru: 'Мох' },
    ],
    sizes: null,
    dims: 'Ø 28 × 42 cm',
    origin: { en: 'Sigulda, Latvia', ru: 'Сигулда, Латвия' },
    weight: 2.4,
    tags: ['new'],
    featured: false,
    createdAt: '2026-06-09',
  },
  {
    id: 'strand-candles',
    sku: 'FJ-LMP-033',
    category: 'lighting',
    material: 'brass',
    name: { en: 'Strand Candleholders, set of 3', ru: 'Подсвечники Strand, набор из 3' },
    blurb: { en: 'Three heights. One conversation.', ru: 'Три высоты. Один разговор.' },
    description: {
      en: 'Turned brass holders in a staggered trio. Weighted bases so a cloth on the table does not become an incident.',
      ru: 'Точёные латунные держатели трёх высот. Утяжелённое основание — скатерть на столе не становится происшествием.',
    },
    care: {
      en: 'Wipe wax with warm water. Patina is intended.',
      ru: 'Воск снимать тёплой водой. Патина задумана.',
    },
    price: 78,
    compareAt: null,
    stock: 22,
    images: [
      u('photo-1603006905003-be475563bc59'),
      u('photo-1602602745782-a7c14eb06712'),
      u('photo-1615485290382-441e4d049cb5'),
    ],
    colors: [{ id: 'brass', hex: '#c4a056', en: 'Brass', ru: 'Латунь' }],
    sizes: null,
    dims: 'H 8 / 14 / 21 cm',
    origin: { en: 'Riga, Latvia', ru: 'Рига, Латвия' },
    weight: 1.1,
    tags: [],
    featured: false,
    createdAt: '2026-03-01',
  },
  {
    id: 'dune-bedding',
    sku: 'FJ-TEX-040',
    category: 'textiles',
    material: 'linen',
    name: { en: 'Dune Linen Bedding', ru: 'Постельное бельё Dune' },
    blurb: { en: 'Washed until it behaves like skin.', ru: 'Стирано, пока не стало как кожа.' },
    description: {
      en: 'European flax, stone-washed in Lithuania, stitched with a quiet flange. It arrives already soft. Set includes duvet cover and two pillowcases.',
      ru: 'Европейский лён, варёный в Литве, с тихим кантом. Приезжает уже мягким. В комплекте пододеяльник и две наволочки.',
    },
    care: {
      en: 'Machine wash 40°C. Line dry. Iron if you must, on damp linen.',
      ru: 'Стирка 40°C. Сушить на линии. Гладить, если нужно, слегка влажным.',
    },
    price: 240,
    compareAt: null,
    stock: 18,
    images: [
      u('photo-1522771739844-6a9f6d5f14af'),
      u('photo-1616627451515-cbc80e5ece35'),
      u('photo-1615873968403-89e068629265'),
    ],
    colors: [
      { id: 'oat', hex: '#e6d8c3', en: 'Oat', ru: 'Овёс' },
      { id: 'clay', hex: '#c9a48a', en: 'Clay', ru: 'Глина' },
      { id: 'night', hex: '#3e3a36', en: 'Night', ru: 'Ночь' },
    ],
    sizes: ['150×200', '200×200', '200×220'],
    dims: 'See size',
    origin: { en: 'Kaunas, Lithuania', ru: 'Каунас, Литва' },
    weight: 2.1,
    tags: ['bestseller'],
    featured: true,
    createdAt: '2025-10-11',
  },
  {
    id: 'fjell-throw',
    sku: 'FJ-TEX-044',
    category: 'textiles',
    material: 'wool',
    name: { en: 'Fjell Wool Throw', ru: 'Плед Fjell' },
    blurb: { en: 'Weight enough to change a room.', ru: 'Достаточный вес, чтобы сменить комнату.' },
    description: {
      en: 'A dense herringbone in undyed Baltic wool. Heavy enough to stay put on a sofa, light enough to travel to the park.',
      ru: 'Плотная ёлочка из некрашеной балтийской шерсти. Достаточно тяжёлый, чтобы лежать на диване, достаточно лёгкий, чтобы поехать в парк.',
    },
    care: {
      en: 'Aired, not washed. If needed: wool cycle, cold, laid flat.',
      ru: 'Проветривать, не стирать. Если нужно — шерстяной цикл, холодно, сушить лёжа.',
    },
    price: 145,
    compareAt: null,
    stock: 20,
    images: [
      u('photo-1584101403633-562f891dc89a'),
      u('photo-1558618666-fcd25c85f82e'),
      u('photo-1615874959474-d609969a20ed'),
    ],
    colors: [
      { id: 'greige', hex: '#b7aea3', en: 'Greige', ru: 'Грейж' },
      { id: 'rust', hex: '#8c4a32', en: 'Rust', ru: 'Ржавчина' },
    ],
    sizes: null,
    dims: '140 × 200 cm',
    origin: { en: 'Viljandi, Estonia', ru: 'Вильянди, Эстония' },
    weight: 1.4,
    tags: [],
    featured: false,
    createdAt: '2026-02-28',
  },
  {
    id: 'coast-curtains',
    sku: 'FJ-TEX-049',
    category: 'textiles',
    material: 'linen',
    name: { en: 'Coast Linen Curtains', ru: 'Шторы Coast' },
    blurb: { en: 'They filter, they do not shut out.', ru: 'Они фильтруют, а не отсекают.' },
    description: {
      en: 'Unlined mid-weight linen that holds a fold and lets the day in as a colour, not a glare. Sold as a pair, pinch-pleat tape included.',
      ru: 'Лён средней плотности без подклада: держит складку и пускает день цветом, а не бликом. Пара, лента под крючки в комплекте.',
    },
    care: {
      en: 'Wash 30°C. Hang while damp to drop the creases.',
      ru: 'Стирка 30°C. Вешать влажными, чтобы ушли заломы.',
    },
    price: 189,
    compareAt: 230,
    stock: 8,
    images: [
      u('photo-1616486338812-3dadae4b4ace'),
      u('photo-1615876234886-fd9a39fda97f'),
      u('photo-1618221195710-dd6b41faaea6'),
    ],
    colors: [
      { id: 'fog', hex: '#d9d2c8', en: 'Fog', ru: 'Туман' },
      { id: 'olive', hex: '#7a7b62', en: 'Olive', ru: 'Олива' },
    ],
    sizes: ['140×250', '140×280'],
    dims: 'Per panel',
    origin: { en: 'Kaunas, Lithuania', ru: 'Каунас, Литва' },
    weight: 1.8,
    tags: ['sale'],
    featured: false,
    createdAt: '2025-07-19',
  },
  {
    id: 'cloud-cushions',
    sku: 'FJ-TEX-052',
    category: 'textiles',
    material: 'wool',
    name: { en: 'Cloud Cushion Set', ru: 'Комплект подушек Cloud' },
    blurb: { en: 'Two squares. One softer argument.', ru: 'Два квадрата. Один мягкий довод.' },
    description: {
      en: 'A pair of feather-filled cushions in a boiled-wool cover with an invisible zip. Sold together because one always looks lonely.',
      ru: 'Пара подушек с пером в варёной шерсти и потайной молнией. Только комплектом — одна всегда выглядит одиноко.',
    },
    care: {
      en: 'Cover: dry clean. Shake daily if you are that person.',
      ru: 'Чехол: химчистка. Взбивать ежедневно, если вы такой человек.',
    },
    price: 96,
    compareAt: null,
    stock: 15,
    images: [
      u('photo-1616627547584-bf28cee262db'),
      u('photo-1584101403633-562f891dc89a'),
      u('photo-1631679706909-1844bbd07221'),
    ],
    colors: [
      { id: 'cream', hex: '#efe6d8', en: 'Cream', ru: 'Крем' },
      { id: 'slate', hex: '#6d7270', en: 'Slate', ru: 'Сланец' },
    ],
    sizes: null,
    dims: '50 × 50 cm × 2',
    origin: { en: 'Riga, Latvia', ru: 'Рига, Латвия' },
    weight: 1.6,
    tags: ['new'],
    featured: false,
    createdAt: '2026-07-02',
  },
  {
    id: 'earth-set',
    sku: 'FJ-CER-060',
    category: 'ceramics',
    material: 'ceramic',
    name: { en: 'Earth Stoneware Set', ru: 'Сервиз Earth' },
    blurb: { en: 'Four places. No matching anxiety.', ru: 'Четыре прибора. Без тревоги комплекта.' },
    description: {
      en: 'Dinner plates, side plates and bowls for four, each thrown and glazed so they belong together without being clones. Speckled oatmeal glaze, food-safe.',
      ru: 'Тарелки, пирожковые и пиалы на четыре персоны — точёные и политые так, чтобы быть семьёй, а не клонами. Крапчатая глазурь oatmeal, пищевая.',
    },
    care: {
      en: 'Dishwasher safe, low. Microwave safe. Avoid thermal shock.',
      ru: 'Посудомойка, щадящий режим. Микроволновка — да. Без термоудара.',
    },
    price: 220,
    compareAt: null,
    stock: 12,
    images: [
      u('photo-1610701596007-11502861dcfa'),
      u('photo-1578749556568-bc2c40e68b61'),
      u('photo-1565193566173-7a0ee3dbe261'),
    ],
    colors: [
      { id: 'oat', hex: '#d9cbb6', en: 'Oatmeal', ru: 'Овсяная' },
      { id: 'ink', hex: '#3d3a36', en: 'Ink', ru: 'Чернила' },
    ],
    sizes: null,
    dims: '12 pieces',
    origin: { en: 'Cesis, Latvia', ru: 'Цесис, Латвия' },
    weight: 6.5,
    tags: ['bestseller'],
    featured: true,
    createdAt: '2026-01-20',
  },
  {
    id: 'pour-jug',
    sku: 'FJ-CER-063',
    category: 'ceramics',
    material: 'ceramic',
    name: { en: 'Pour Jug', ru: 'Кувшин Pour' },
    blurb: { en: 'Water, wine, branches — it does not ask.', ru: 'Вода, вино, ветки — он не спрашивает.' },
    description: {
      en: 'A generous stoneware jug with a pulled handle and a lip that actually pours. The glaze breaks on the rim the way good studio pots do.',
      ru: 'Просторный кувшин из каменной массы с вытянутой ручкой и носиком, который правда льёт. Глазурь ломается на кромке, как у хорошей студийной посуды.',
    },
    care: {
      en: 'Dishwasher safe. Not for the hob.',
      ru: 'Посудомойка — да. На плиту — нет.',
    },
    price: 64,
    compareAt: null,
    stock: 19,
    images: [
      u('photo-1604578762246-41134e37f9cc'),
      u('photo-1610701596061-2ecf227e85b2'),
      u('photo-1615485290382-441e4d049cb5'),
    ],
    colors: [
      { id: 'cream', hex: '#eee4d4', en: 'Cream', ru: 'Крем' },
      { id: 'rust', hex: '#a35a3a', en: 'Rust', ru: 'Ржавчина' },
    ],
    sizes: null,
    dims: '1.4 L, H 22 cm',
    origin: { en: 'Sigulda, Latvia', ru: 'Сигулда, Латвия' },
    weight: 0.9,
    tags: [],
    featured: false,
    createdAt: '2026-03-17',
  },
  {
    id: 'moss-bowls',
    sku: 'FJ-CER-066',
    category: 'ceramics',
    material: 'ceramic',
    name: { en: 'Moss Tea Bowls, set of 4', ru: 'Пиалы Moss, 4 шт.' },
    blurb: { en: 'For tea, or last night’s plums.', ru: 'Для чая или вчерашних слив.' },
    description: {
      en: 'Small deep bowls with a celadon-leaning glaze. They nest. They also look right empty on a shelf, which is a test most bowls fail.',
      ru: 'Маленькие глубокие пиалы с глазурью в сторону селадона. Складываются стопкой. И пустые на полке выглядят правильно — этот экзамен большинство пиал проваливает.',
    },
    care: {
      en: 'Dishwasher and microwave safe.',
      ru: 'Посудомойка и микроволновка — да.',
    },
    price: 52,
    compareAt: null,
    stock: 24,
    images: [
      u('photo-1610701596061-2ecf227e85b2'),
      u('photo-1565193566173-7a0ee3dbe261'),
      u('photo-1578749556568-bc2c40e68b61'),
    ],
    colors: [{ id: 'moss', hex: '#6d7a62', en: 'Moss', ru: 'Мох' }],
    sizes: null,
    dims: 'Ø 11 × 6 cm × 4',
    origin: { en: 'Cesis, Latvia', ru: 'Цесис, Латвия' },
    weight: 1.0,
    tags: [],
    featured: false,
    createdAt: '2026-04-04',
  },
  {
    id: 'silo-vase',
    sku: 'FJ-CER-071',
    category: 'ceramics',
    material: 'ceramic',
    name: { en: 'Silo Floor Vase', ru: 'Напольная ваза Silo' },
    blurb: { en: 'Architecture for branches.', ru: 'Архитектура для веток.' },
    description: {
      en: 'A tall, slightly swollen cylinder in unglazed grogged clay. Weighted so a winter branch does not tip the whole affair.',
      ru: 'Высокий, слегка раздутый цилиндр из шамотной глины без глазури. Утяжелён, чтобы зимняя ветка не опрокинула всю конструкцию.',
    },
    care: {
      en: 'Wipe dust. Water-tight liner included.',
      ru: 'Смахивать пыль. Внутри — герметичный вкладыш.',
    },
    price: 118,
    compareAt: null,
    stock: 6,
    images: [
      u('photo-1604578762246-41134e37f9cc'),
      u('photo-1615485290382-441e4d049cb5'),
      u('photo-1519710164239-da123dc03ef4'),
    ],
    colors: [
      { id: 'clay', hex: '#b08968', en: 'Raw clay', ru: 'Сырая глина' },
      { id: 'ash', hex: '#9a958c', en: 'Ash', ru: 'Пепел' },
    ],
    sizes: null,
    dims: 'Ø 22 × 62 cm',
    origin: { en: 'Riga, Latvia', ru: 'Рига, Латвия' },
    weight: 4.8,
    tags: ['new'],
    featured: true,
    createdAt: '2026-06-21',
  },
  {
    id: 'board-oak',
    sku: 'FJ-ACC-080',
    category: 'accessories',
    material: 'oak',
    name: { en: 'Board Oak Serving', ru: 'Сервировочная доска Board' },
    blurb: { en: 'Bread, cheese, a Tuesday.', ru: 'Хлеб, сыр, вторник.' },
    description: {
      en: 'A long serving board in end-and-face grain oak, finished with food-safe oil. A shallow juice groove, a leather strap, nothing else.',
      ru: 'Длинная доска из дуба в смешанном распиле, пищевое масло. Неглубокий жёлоб для сока, кожаная петля — и всё.',
    },
    care: {
      en: 'Hand wash, dry upright, oil when thirsty.',
      ru: 'Мыть руками, сушить стоя, масло — когда просит.',
    },
    price: 72,
    compareAt: null,
    stock: 17,
    images: [
      u('photo-1467043153537-a4fba2cd39ef'),
      u('photo-1611967164521-abae8fba4668'),
      u('photo-1615485290382-441e4d049cb5'),
    ],
    colors: [{ id: 'oak', hex: '#c4a574', en: 'Oak', ru: 'Дуб' }],
    sizes: null,
    dims: '55 × 18 × 2.2 cm',
    origin: { en: 'Kuldiga, Latvia', ru: 'Кулдига, Латвия' },
    weight: 1.2,
    tags: [],
    featured: false,
    createdAt: '2025-12-14',
  },
  {
    id: 'tray-brass',
    sku: 'FJ-ACC-084',
    category: 'accessories',
    material: 'brass',
    name: { en: 'Oval Brass Tray', ru: 'Овальный поднос' },
    blurb: { en: 'Catches keys, light, and blame.', ru: 'Собирает ключи, свет и вину.' },
    description: {
      en: 'A shallow oval in hand-beaten brass. It lives on a console or in the middle of the Havn table and slowly records every fingerprint.',
      ru: 'Неглубокий овал из ручной латуни. Живёт на консоли или в центре стола Havn и медленно записывает каждый отпечаток.',
    },
    care: {
      en: 'Polish or don’t. Both are correct.',
      ru: 'Полировать или нет. Оба ответа верны.',
    },
    price: 88,
    compareAt: null,
    stock: 13,
    images: [
      u('photo-1616046444654-65e6895d6b0d'),
      u('photo-1603006905003-be475563bc59'),
      u('photo-1556228453-efd6c1ff04f6'),
    ],
    colors: [{ id: 'brass', hex: '#c4a056', en: 'Brass', ru: 'Латунь' }],
    sizes: null,
    dims: '38 × 24 cm',
    origin: { en: 'Helsinki', ru: 'Хельсинки' },
    weight: 0.7,
    tags: [],
    featured: false,
    createdAt: '2026-02-02',
  },
  {
    id: 'mira-mirror',
    sku: 'FJ-ACC-090',
    category: 'accessories',
    material: 'oak',
    name: { en: 'Mira Wall Mirror', ru: 'Зеркало Mira' },
    blurb: { en: 'A second window, this time honest.', ru: 'Второе окно, на этот раз честное.' },
    description: {
      en: 'A tall arched mirror in a slim oak frame. Lean it or hang it. The glass is copper-backed, slightly warmer than a cheap silver.',
      ru: 'Высокое арочное зеркало в тонкой дубовой раме. Прислонить или повесить. Стекло с медной амальгамой — чуть теплее дешёвого серебра.',
    },
    care: {
      en: 'Glass cleaner on the glass only. Frame: dry cloth.',
      ru: 'Средство для стёкол — только на стекло. Рама — сухая ткань.',
    },
    price: 260,
    compareAt: null,
    stock: 7,
    images: [
      u('photo-1618221381711-42ca8ab6e908'),
      u('photo-1616486338812-3dadae4b4ace'),
      u('photo-1600210492486-724fe5c67fb0'),
    ],
    colors: [
      { id: 'oak', hex: '#c4a574', en: 'Oak', ru: 'Дуб' },
      { id: 'black', hex: '#2a2825', en: 'Black oak', ru: 'Чёрный дуб' },
    ],
    sizes: null,
    dims: '60 × 160 cm',
    origin: { en: 'Riga, Latvia', ru: 'Рига, Латвия' },
    weight: 11,
    tags: ['bestseller'],
    featured: false,
    createdAt: '2025-11-28',
  },
  {
    id: 'horisont-clock',
    sku: 'FJ-ACC-093',
    category: 'accessories',
    material: 'oak',
    name: { en: 'Horisont Wall Clock', ru: 'Часы Horisont' },
    blurb: { en: 'Time, without shouting.', ru: 'Время без крика.' },
    description: {
      en: 'A silent quartz movement behind a pale oak face and two thin steel hands. No numerals. You already know what o’clock it is.',
      ru: 'Бесшумный кварц, светлый дубовый циферблат и две тонкие стальные стрелки. Без цифр. Вы и так знаете, который час.',
    },
    care: {
      en: 'Dust. One AA battery, included.',
      ru: 'Пыль. Одна батарея AA — в комплекте.',
    },
    price: 134,
    compareAt: null,
    stock: 11,
    images: [
      u('photo-1565193566173-7a0ee3dbe261'),
      u('photo-1519710164239-da123dc03ef4'),
      u('photo-1556228453-efd6c1ff04f6'),
    ],
    colors: [{ id: 'oak', hex: '#e6d4b8', en: 'Pale oak', ru: 'Светлый дуб' }],
    sizes: null,
    dims: 'Ø 40 cm',
    origin: { en: 'Riga, Latvia', ru: 'Рига, Латвия' },
    weight: 1.3,
    tags: [],
    featured: false,
    createdAt: '2026-05-19',
  },
  {
    id: 'ember-incense',
    sku: 'FJ-ACC-097',
    category: 'accessories',
    material: 'ceramic',
    name: { en: 'Ember Incense Set', ru: 'Набор Ember' },
    blurb: { en: 'Pine, smoke, a closed door.', ru: 'Сосна, дым, закрытая дверь.' },
    description: {
      en: 'A small stoneware boat and a tin of Baltic pine incense sticks. Twenty minutes of forest in a city apartment.',
      ru: 'Маленькая каменная лодочка и банка с палочками из балтийской сосны. Двадцать минут леса в городской квартире.',
    },
    care: {
      en: 'Never leave a burning stick unattended. Refills in the shop.',
      ru: 'Не оставлять горящую палочку без присмотра. Сменные блоки — в магазине.',
    },
    price: 42,
    compareAt: null,
    stock: 30,
    images: [
      u('photo-1603006905003-be475563bc59'),
      u('photo-1610701596007-11502861dcfa'),
      u('photo-1615485290382-441e4d049cb5'),
    ],
    colors: [{ id: 'clay', hex: '#a88462', en: 'Clay', ru: 'Глина' }],
    sizes: null,
    dims: 'Holder 14 cm + 30 sticks',
    origin: { en: 'Riga, Latvia', ru: 'Рига, Латвия' },
    weight: 0.4,
    tags: ['new'],
    featured: false,
    createdAt: '2026-07-28',
  },
  {
    id: 'ridge-bookends',
    sku: 'FJ-ACC-101',
    category: 'accessories',
    material: 'oak',
    name: { en: 'Ridge Bookends', ru: 'Букенды Ridge' },
    blurb: { en: 'Two weights for a leaning life.', ru: 'Два груза для жизни под наклоном.' },
    description: {
      en: 'A pair of solid oak blocks with a felted base and just enough mass to keep a row of books honest.',
      ru: 'Пара дубовых блоков с войлоком снизу и достаточной массой, чтобы ряд книг оставался честным.',
    },
    care: {
      en: 'Wipe. Do not use as a doorstop unless you mean it.',
      ru: 'Протирать. Не использовать как ограничитель двери — если только вы этого не хотите.',
    },
    price: 58,
    compareAt: null,
    stock: 14,
    images: [
      u('photo-1467043153537-a4fba2cd39ef'),
      u('photo-1594026112284-02bb6f3352fe'),
      u('photo-1519710164239-da123dc03ef4'),
    ],
    colors: [{ id: 'oak', hex: '#c4a574', en: 'Oak', ru: 'Дуб' }],
    sizes: null,
    dims: '10 × 10 × 16 cm × 2',
    origin: { en: 'Cesis, Latvia', ru: 'Цесис, Латвия' },
    weight: 2.6,
    tags: [],
    featured: false,
    createdAt: '2026-03-30',
  },
]

export const SEED_REVIEWS = {
  'arhus-lounge': [
    { id: 'r1', name: 'Elīna K.', stars: 5, date: '2026-05-12', en: 'Lower than I expected, in the best way. I read here every night.', ru: 'Ниже, чем ждала — и это лучшее. Читаю здесь каждый вечер.' },
    { id: 'r2', name: 'Mārtiņš', stars: 4, date: '2026-04-02', en: 'Fabric is honest. The ink colour hides life better than clay.', ru: 'Ткань честная. Цвет «чернила» лучше прячет жизнь, чем «глина».' },
  ],
  'kalmar-table': [
    { id: 'r3', name: 'Anna P.', stars: 5, date: '2026-03-18', en: 'We took 220 cm. Six people, no theatre, as promised.', ru: 'Взяли 220 см. Шестеро, без театра — как обещали.' },
  ],
  'norr-sofa': [
    { id: 'r4', name: 'Jonas', stars: 5, date: '2026-06-01', en: 'Finally a modular that does not look like office furniture.', ru: 'Наконец модульный, который не выглядит офисной мебелью.' },
    { id: 'r5', name: 'Саша', stars: 4, date: '2026-05-22', en: 'Deep sit. Covers came off easily after a red-wine incident.', ru: 'Глубокая посадка. Чехлы легко снялись после инцидента с вином.' },
  ],
  'lumen-floor': [
    { id: 'r6', name: 'Ieva', stars: 5, date: '2026-02-11', en: 'Turns the room into evening. That is all I wanted.', ru: 'Делает из комнаты вечер. Это всё, чего я хотела.' },
  ],
  'dune-bedding': [
    { id: 'r7', name: 'Olga', stars: 5, date: '2026-01-09', en: 'Soft on arrival. Washed twice, still the same colour.', ru: 'Мягкое сразу. Два раза стирала — цвет тот же.' },
    { id: 'r8', name: 'Tom', stars: 4, date: '2025-12-20', en: 'Night colour is almost black in the evening. Beautiful.', ru: 'Цвет «ночь» вечером почти чёрный. Красиво.' },
  ],
  'earth-set': [
    { id: 'r9', name: 'Kristīne', stars: 5, date: '2026-04-14', en: 'They do not match perfectly. That is why they work.', ru: 'Они не идеально одинаковые. Поэтому и работают.' },
  ],
  'mira-mirror': [
    { id: 'r10', name: 'Paul', stars: 5, date: '2026-03-03', en: 'Leaning against the bedroom wall. Makes the room twice as long.', ru: 'Стоит у стены в спальне. Комната стала вдвое длиннее.' },
  ],
}

export function productById(id) {
  return PRODUCTS.find((p) => p.id === id)
}
